export const NAV_LINKS = [
  { label: 'طريقتنا', labelEn: 'Method', href: '#method' },
  { label: 'البرامج', labelEn: 'Programs', href: '#tracks' },
  { label: 'معرض الإنجازات', labelEn: 'Showcase', href: '#showcase' },
  { label: 'من الورش', labelEn: 'From Workshops', href: '#students' },
  { label: 'لأولياء الأمور', labelEn: 'For Parents', href: '#parents' },
];

export const MARQUEE_ITEMS = ['Software', 'Embedded', 'IoT', 'Robotics', 'AI'];

export const METHOD_STEPS = [
  {
    num: 'WHY',
    icon: '🎯',
    title: 'ليه محتاجين ده؟',
    titleEn: 'Why do we need this?',
    desc: 'الطالب بيشوف مشروع ناقصه حاجة — ومحسّه بالاحتياج قبل ما يسمع اسم المفهوم.',
    descEn: 'Students encounter a project with a missing piece — feeling the need before even hearing the concept name.',
  },
  {
    num: 'WHAT',
    icon: '🧩',
    title: 'إيه المفهوم؟',
    titleEn: 'What is the concept?',
    desc: 'المفهوم بيتسمى بس بعد ما الطالب حس إنه محتاجه — مش قبلها.',
    descEn: 'The technical concept is named only after students realize they need it — never before.',
  },
  {
    num: 'HOW',
    icon: '⚙️',
    title: 'إزاي نستخدمه؟',
    titleEn: 'How do we use it?',
    desc: 'تطبيق مباشر على المشروع الحقيقي، مش تمرين منفصل عن السياق.',
    descEn: 'Direct hands-on application on the actual project, not an isolated out-of-context exercise.',
  },
  {
    num: 'BUILD',
    icon: '🚀',
    title: 'نبنيه',
    titleEn: 'Build It',
    desc: 'المشروع بيكتمل ويتدمج فعلياً — مش تمرين بيتنسى بعد الحصة.',
    descEn: 'The project is fully integrated and completed — a real working product, not a forgotten assignment.',
  },
];

export const DEFAULT_TRACKS = [
  {
    id: 1,
    tag: 'Software',
    title: 'مسار البرمجة',
    titleEn: 'Software Engineering',
    desc: 'بناء ألعاب وتطبيقات حقيقية — من أول سطر كود لمنتج شغال.',
    descEn: 'Building real games and applications — from the first line of code to a working product.',
    ageLabel: 'الفئة العمرية',
    ageLabelEn: 'Age Group',
    ageValue: '10 – 14',
  },
  {
    id: 2,
    tag: 'Embedded / IoT',
    title: 'مسار الأنظمة المدمجة',
    titleEn: 'Embedded & IoT Systems',
    desc: 'دوائر إلكترونية وأجهزة متصلة بالإنترنت — يبنوا ويشغلوا بإيدهم.',
    descEn: 'Electronic circuits and connected IoT hardware — designed and wired by students.',
    ageLabel: 'يشمل كِت أدوات',
    ageLabelEn: 'Includes Hardware Kit',
    ageValue: '✓',
  },
  {
    id: 3,
    tag: 'Robotics',
    title: 'مسار الروبوتيكس',
    titleEn: 'Robotics Engineering',
    desc: 'تصميم وبرمجة روبوتات حقيقية، تجهيز للمسابقات المحلية والدولية.',
    descEn: 'Designing and programming real robots, preparing for regional and global competitions.',
    ageLabel: 'الفئة العمرية',
    ageLabelEn: 'Age Group',
    ageValue: '12 – 18',
  },
  {
    id: 4,
    tag: 'AI',
    title: 'مسار الذكاء الاصطناعي',
    titleEn: 'Artificial Intelligence',
    desc: 'بناء وتدريب نماذج بسيطة وتطبيقها على مشاكل حقيقية.',
    descEn: 'Building and training AI models applied directly to real-world challenges.',
    ageLabel: 'الفئة العمرية',
    ageLabelEn: 'Age Group',
    ageValue: '15 – 18',
  },
  {
    id: 5,
    tag: 'Explorer',
    title: 'مسار الاستكشاف',
    titleEn: 'Junior Explorer Track',
    desc: 'أول خطوة في عالم الصنعة — بأسلوب بصري وممتع مناسب لسنهم.',
    descEn: 'The first step into making — visual, fun, and tailored for younger minds.',
    ageLabel: 'الفئة العمرية',
    ageLabelEn: 'Age Group',
    ageValue: '6 – 9',
  },
  {
    id: 6,
    tag: 'Capstone',
    title: 'مشروع التخرج',
    titleEn: 'Capstone Graduation',
    desc: 'مشروع متكامل من الفكرة للإطلاق — يُقدَّم فعلياً أو يُعرض في مسابقة.',
    descEn: 'End-to-end product development from idea to launch, submitted for competition.',
    ageLabel: 'نهاية المسار',
    ageLabelEn: 'Track Outcome',
    ageValue: '—',
  },
];

export const SHOWCASE_PROJECTS = [
  {
    id: 1,
    tag: 'Software',
    icon: '🎮',
    status: 'مكتمل',
    statusEn: 'Completed',
    title: 'لعبة عداد النقاط',
    titleEn: 'Score Tracker Game',
    desc: 'لعبة تفاعلية بتحسب نقط اللاعب لحظياً وبتزوّد الصعوبة كل ما يتقدم.',
    descEn: 'Interactive game tracking player scores in real-time with dynamic difficulty.',
    makerCount: '12',
    starterIdea: 'لعبة ناقصها ذاكرة',
    starterIdeaEn: 'A game missing persistent score memory',
  },
  {
    id: 2,
    tag: 'Robotics',
    icon: '🤖',
    status: 'مكتمل',
    statusEn: 'Completed',
    title: 'روبوت متتبع خط',
    titleEn: 'Line-Following Robot',
    desc: 'روبوت بيتحرك ويصحح مساره لوحده باستخدام حساسات، جاهز للمسابقات.',
    descEn: 'Autonomous line-tracking robot auto-correcting path with IR sensors.',
    makerCount: '14',
    starterIdea: 'روبوت تايه عن مساره',
    starterIdeaEn: 'A robot lost without direction sensors',
  },
  {
    id: 3,
    tag: 'IoT',
    icon: '💡',
    status: 'مكتمل',
    statusEn: 'Completed',
    title: 'نظام إنارة ذكي',
    titleEn: 'Smart Lighting System',
    desc: 'إنارة بتشتغل وتقفل أوتوماتيك حسب وجود حد في الأوضة، موصولة بحساس حركة.',
    descEn: 'Automated room lighting triggered by occupancy sensors and IoT relays.',
    makerCount: '15',
    starterIdea: 'أوضة بتنسى تقفل نفسها',
    starterIdeaEn: 'A room that forgets to turn lights off',
  },
  {
    id: 4,
    tag: 'Software',
    icon: '📱',
    status: 'مكتمل',
    statusEn: 'Completed',
    title: 'تطبيق تذكير بالمواعيد',
    titleEn: 'Task Reminder App',
    desc: 'تطبيق بيبعت تنبيه في وقت محدد، صممه الطالب عشان مشكلة حقيقية بتحصله.',
    descEn: 'Custom scheduler app sending notifications at specified intervals.',
    makerCount: '11',
    starterIdea: 'بننسى المواعيد',
    starterIdeaEn: 'Forgetting important session dates',
  },
  {
    id: 5,
    tag: 'AI',
    icon: '🧠',
    status: 'مكتمل',
    statusEn: 'Completed',
    title: 'نموذج تمييز الصور',
    titleEn: 'Image Recognition Model',
    desc: 'نموذج ذكاء اصطناعي بيفرّق بين نوعين من الأشياء اعتماداً على صور دربه عليها الطالب.',
    descEn: 'Computer vision model classifying objects trained on custom student datasets.',
    makerCount: '17',
    starterIdea: 'الكاميرا مش فاهمة اللي بتشوفه',
    starterIdeaEn: 'Camera unable to distinguish objects',
  },
  {
    id: 6,
    tag: 'Embedded',
    icon: '⚙️',
    status: 'مكتمل',
    statusEn: 'Completed',
    title: 'ذراع آلية بسيطة',
    titleEn: 'Robotic Arm Manipulator',
    desc: 'ذراع ميكانيكية بتتحكم فيها عن بُعد، بُنيت لحل مهمة نقل بسيطة.',
    descEn: 'Servo-driven mechanical arm remotely controlled for pick-and-place tasks.',
    makerCount: '13',
    starterIdea: 'شيل ده من هنا بلاش ما ألمسه',
    starterIdeaEn: 'Safely moving objects without touch',
  },
];

export const PARENT_POINTS = [
  'ابنك مش هيتعلم الكود بس، هيتعلم يفكر ويحل مشاكل لوحده.',
  'كل تيرم بيخلص بمشروع حقيقي تقدر تشوفه بعينك، مش امتحان.',
  'متابعة مستمرة لتقدمه عن طريق "جواز صانع" — سجل حي مش شهادة ثابتة.',
  'مدربين مؤهلين بيتابعوا كل طالب فردياً، مش شرح جماعي بس.',
];

export const PARENT_POINTS_EN = [
  'Your child will not just learn code; they learn to think and solve complex problems independently.',
  'Every semester concludes with a working project you can test, not a theoretical exam.',
  'Continuous progress tracking via the "Sanea Passport" — a live evidence portfolio.',
  'Expert engineering mentors providing individual 1-on-1 guidance.',
];

export const WORKSHOP_SLOTS = [
  { id: 1, span: 2, title: 'صورة من ورشة الروبوتيكس', titleEn: 'Robotics Workshop Session' },
  { id: 2, span: 1, title: 'مشروع طالب', titleEn: 'Student Project Build' },
  { id: 3, span: 1, title: 'حصة برمجة', titleEn: 'Coding Session' },
  { id: 4, span: 1, title: 'يوم العرض النهائي', titleEn: 'Final Demo Day Showcase' },
  { id: 5, span: 2, title: 'لحظة إنجاز — مشروع اكتمل', titleEn: 'Moment of Craft — Completed Build' },
];
